---
title: "Data_Wrangling"
author: "Yujing Wu"
date: "11/23/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyr)
library(tidyverse)
library(sf)
library(RSocrata)
library(lubridate)
library(tigris)
library(tidycensus)
library(gganimate)
library(viridis)
library(riem)
library(gridExtra)
library(knitr)
library(kableExtra)
library(reshape2)
#library(stargazer)

mapTheme <- function(base_size = 12) {
  theme(
    text = element_text( color = "black"),
    plot.title = element_text(size = 14,colour = "black"),
    plot.subtitle=element_text(face="italic"),
    plot.caption=element_text(hjust=0),
    axis.ticks = element_blank(),
    panel.background = element_blank(),axis.title = element_blank(),
    axis.text = element_blank(),
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    panel.grid.minor = element_blank(),
    panel.border = element_rect(colour = "black", fill=NA, size=2)
  )
}

plotTheme <- function(base_size = 12) {
  theme(
    text = element_text( color = "black"),
    plot.title = element_text(size = 14,colour = "black"),
    plot.subtitle = element_text(face="italic"),
    plot.caption = element_text(hjust=0),
    axis.ticks = element_blank(),
    panel.background = element_blank(),
    panel.grid.major = element_line("grey80", size = 0.1),
    panel.grid.minor = element_blank(),
    panel.border = element_rect(colour = "black", fill=NA, size=2),
    strip.background = element_rect(fill = "grey80", color = "white"),
    strip.text = element_text(size=12),
    axis.title = element_text(size=12),
    axis.text = element_text(size=10),
    plot.background = element_blank(),
    legend.background = element_blank(),
    legend.title = element_text(colour = "black", face = "italic"),
    legend.text = element_text(colour = "black", face = "italic"),
    strip.text.x = element_text(size = 14)
  )
}
palette = c('#1f638e', '#4b95c2', '#84c8f6', '#fab5a0', '#fe6843', '#dc0000')
```

```{r}
boundary <- st_read('https://opendata.arcgis.com/datasets/82ada480c5344220b2788154955ce5f0_8.geojson') %>%
  st_set_crs(4326) %>%
   st_transform(2284)
```

```{r}
Daytimepop <- st_read('Data\\Daytimepop.shp') %>%
   st_transform(2284)
```

```{r}
Zoning <- st_read('https://opendata.arcgis.com/datasets/a3558a2790384bd0950cbdbe69e29da8_2.geojson') %>%
   st_transform(2284)
```

```{r}
Neighborhoods <- st_read('https://data.opendatasoft.com/explore/dataset/zillow-neighborhoods@public/download/?format=geojson&refine.state=VA&refine.county=Virginia+Beach+City&timezone=America/New_York')  %>%
   st_transform(2284)
```

```{r}
accident <- st_read("https://opendata.arcgis.com/datasets/1c7c9f723d5947c19c0fc34aaa30ff2a_0.geojson?where=Crash_Severity%20like%20'%25A.Severe%20Injury%25'%20AND%20VDOT_District%20like%20'%255.Hampton%20Roads%25'%20AND%20Crash_Year%20%3E%3D%202017%20AND%20Crash_Year%20%3C%3D%202017") %>%
   st_transform(2284)
```

```{r}
fishnet <- 
  st_make_grid(boundary, cellsize = 5000) %>%
  st_sf()

fishnet <- 
  fishnet[boundary,] %>%
  mutate(uniqueID = rownames(.)) %>%
  dplyr::select(uniqueID)

fishnet <- fishnet %>%
  st_join(Neighborhoods[2], st_intersects, largest = TRUE)

fishnet <- fishnet %>%
  st_join(Daytimepop[c('DPOP_CY')], st_intersects, largest = TRUE)

accident_net <- 
  accident %>% 
  dplyr::select() %>% 
  mutate(countAccident = 1) %>% 
  aggregate(., fishnet, sum) %>%
  mutate(countAccident = ifelse(is.na(countAccident), 0, countAccident),
         uniqueID = rownames(.)) 

fishnet <- fishnet %>%
  merge(st_set_geometry(accident_net, NULL), by = 'uniqueID')
```

```{r}
ggplot() +
  geom_sf(data=fishnet, aes(fill = countAccident)) +
  mapTheme()
```

```{r}
EMS_calls <- read.socrata("https://data.vbgov.com/Public-Safety/EMS-Calls-For-Service/2wub-c2dx") %>%
  mutate(year = substr(call_date_and_time,1,4)) %>%
  filter(year == "2017") %>%
  mutate(x = gsub("^.*\\(\\s*", "", location_1)) %>%
  mutate(x = gsub("[)]", "", x)) %>%
  mutate(x = gsub("[a-zA-Z]", "", x)) %>%
  separate(x, c("Y","X"), sep=",") %>%
  mutate(X = as.numeric(X),
          Y = as.numeric(Y)) %>% 
   na.omit %>%
   st_as_sf(coords = c("X", "Y"), crs = 4326) %>%
   st_transform(2284)
```

```{r}
vbCensus <- 
  get_acs(geography = "tract", variables = c("B01003_001", "B19013_001", "B02001_002", "B08013_001",                                                        "B08012_001", "B08301_001", "B08301_010", "B11007_001", "B12001_003", "B12001_007", "B12001_009", "B12001_010"), 
          year = 2017, state = "VA", geometry = TRUE, county=c("Virginia Beach")) %>%
  mutate(variable = 
          case_when(variable == "B01003_001" ~ "Total_Population",
                    variable == "B19013_001" ~ "Median_Household_Income",
                    variable == "B02001_002" ~ "Total_White_Population",
                    variable == "B08301_001" ~ "Means_of_Transportation_to_Work",
                    variable == "B08301_010" ~ "Total_Public_Trans_excl_Taxi",
                    variable == "B11007_001" ~ "Total_Households_with_65yrs_and_Over",
                    variable == "B12001_003" ~ "Never_Married_Male",
                    variable == "B12001_007" ~ "Spouse_Absent_Male", 
                    variable == "B12001_009" ~ "Widowed_Male",
                    variable == "B12001_010" ~ "Divorced_Male")) %>%
  select(variable, estimate, GEOID, geometry) %>%
  spread(variable,estimate) %>%
  mutate(Percent_White = Total_White_Population / Total_Population,
         Percent_Taking_Public_Trans = Total_Public_Trans_excl_Taxi / Means_of_Transportation_to_Work,
         Percent_Single_Male = (Never_Married_Male + Spouse_Absent_Male + Widowed_Male + Divorced_Male)/Total_Population) %>%
  gather(Variable,Value, -GEOID, -geometry) %>%
  st_transform(2284)
```

```{r}
vbTracts <- 
  vbCensus %>%
  as.data.frame() %>%
  distinct(GEOID, .keep_all = TRUE) %>%
  select(GEOID, geometry) %>% 
  st_sf()
```

```{r}
weather.Data <- 
  riem_measures(station = "NTU", date_start = "2017-01-01", date_end = "2018-01-01")
```

```{r}
weather.Panel <-  
  weather.Data %>%
    replace(is.na(.), 0) %>%
    mutate(interval60 = ymd_h(substr(valid,1,13))) %>%
    mutate(week = week(interval60),
           dotw = wday(interval60, label=TRUE)) %>%
    group_by(interval60) %>%
    summarize(Temperature = max(tmpf),
              Percipitation = sum(p01i),
              Wind_Speed = max(sknt)) %>%
    mutate(Temperature = ifelse(Temperature == 0, 42, Temperature))
```

```{r}
EMS_calls2 <-
  EMS_calls %>% 
  mutate(interval60 = floor_date(ymd_hms(call_date_and_time), unit = "hour"),
         interval15 = floor_date(ymd_hms(call_date_and_time), unit = "15 mins"),
         week = week(interval60),
         dotw = wday(interval60, label=TRUE))
```

```{r}
EMS_fishnet <-
  EMS_calls2 %>% 
  st_join(fishnet, st_intersects) %>% 
  st_set_geometry(NULL)
```

```{r}
EMS.template <- 
  EMS_fishnet %>%
  filter(week >= 22 & week <= 24 | week >= 25 & week <= 30)
```

```{r}
study.panel <- 
  expand.grid(interval60 = seq(floor_date(ymd_hms(min(EMS.template$call_date_and_time)), unit = "hour"),floor_date(ymd_hms(max(EMS.template$call_date_and_time)), unit = "hour"), by = '60 mins'), 
              uniqueID = unique(fishnet$uniqueID)) 

nrow(study.panel)   
```

```{r}
EMS_Call.panel <- 
  EMS.template %>%
    mutate(Call_Counter = 1) %>%
    right_join(study.panel) %>% 
      group_by(interval60, uniqueID) %>%
      summarize(Call_Count = sum(Call_Counter, na.rm=T)) %>%
      left_join(weather.Panel) %>%
      left_join(fishnet, by=c("uniqueID")) %>%
            ungroup() %>%                                 
            mutate(week = week(interval60),
                   dotw = wday(interval60, label = TRUE)) %>%
            st_sf()
```

```{r}
EMS_Call.panel <- 
  EMS_Call.panel %>% 
    arrange(uniqueID, interval60) %>% 
    mutate(lagHour = dplyr::lag(Call_Count,1),
           lag2Hours = dplyr::lag(Call_Count,2),
           lag3Hours = dplyr::lag(Call_Count,3),
           lag4Hours = dplyr::lag(Call_Count,4),
           lag12Hours = dplyr::lag(Call_Count,12),
           lag1day = dplyr::lag(Call_Count,24)) %>%
    mutate(day = yday(interval60)) 
```

```{r}
Rescue_stations <- st_read('Data\\Rescue_stations.shp') %>%
   st_transform(2284)
```

```{r, fig.width= 18, fig.height=4}
mondayMidnight <- 
  EMS_Call.panel %>%
  mutate(mondayMidnight = ifelse(wday(interval60) == 2 & hour(interval60) == 1,
                                 as.POSIXct(interval60),0)) %>%
  filter(mondayMidnight != 0) 

  rbind(
    mutate(EMS_Call.Train, label = "Training"), 
    mutate(EMS_Call.Test, label = "Testing")) %>%
      group_by(label, interval60) %>% 
        summarize(Call_Count = sum(Call_Count)) %>%
        ggplot(aes(interval60, Call_Count, colour = label)) + 
          geom_line() +
          ylim(0,20) +
          labs(title="EMS calls in Virginia Beach by week: June through August, 2018",
               subtitle="Monday demarked in black", x="Day", y="Call Counts") +
          plotTheme() + theme(panel.grid.major = element_blank()) +   
          scale_colour_manual(values = palette2) +
            geom_vline(data = mondayMidnight, aes(xintercept = mondayMidnight), colour="black")
```

```{r}
as.data.frame(EMS_Call.panel) %>%
  group_by(week, interval60) %>% 
  summarize(Call_Count = sum(Call_Count)) %>%
    ggplot(aes(interval60,Call_Count)) + 
      geom_line() +
      plotTheme() +
      facet_wrap(~week, scales="free", ncol=3) +
      ylim(0,20) +
      labs(title="EMS Calls in Virginia Beach by week: June to August, 2017",
            x="Day", y="Trip Counts") 
```

```{r}
plotData.lag <-
  as.data.frame(EMS_Call.panel) %>%
  filter(week == 26) %>%
  group_by(interval60) %>% 
    summarise_at(vars(starts_with("lag"), "Call_Count"), mean, na.rm = TRUE) %>%
    gather(Variable, Value, -interval60, -Call_Count) %>%
    mutate(Variable = factor(Variable, levels=c("lagHour","lag2Hours","lag3Hours","lag4Hours",
                                                "lag12Hours","lag1day")))

correlation.lag <-
  plotData.lag %>%
  group_by(Variable) %>%  
  summarize(correlation = round(cor(Value, Call_Count),2))
  
correlation.lag
```

```{r}
plotData.lag %>%
  ggplot(aes(Value, Call_Count)) + 
    geom_point() + geom_smooth(method = "lm", se = F) + 
    facet_wrap(~Variable) +
    geom_text(data=correlation.lag, aes(label=paste("R =", correlation)),colour = "blue", 
              x=-Inf, y=Inf, hjust=-0.1, vjust=1.2) +
    labs(title = "EMS call count as a function of time lags", 
         subtitle= "One week in June, 2017", x = "Lag Call Count") +
    plotTheme()
```

```{r, fig.width=15, fig.height=15}
EMS_Call.panel %>%
  mutate(hour = hour(interval60)) %>%
  group_by(hour, uniqueID) %>%
  summarize(Sum_Call_Count = sum(Call_Count)) %>%
  ggplot() + geom_sf(aes(fill = Sum_Call_Count)) +
    facet_wrap(~hour, ncol = 4) +
    scale_fill_viridis() +
    labs(title="Sum of EMS calls by hour of the day") +
    mapTheme() + theme(legend.position = "bottom") 
```

```{r, fig.width=15, fig.height=15}
EMS_Call.panel %>% 
  group_by(dotw, uniqueID) %>%
  summarize(Sum_Call_Count = sum(Call_Count)) %>%
  ggplot() + geom_sf(aes(fill = Sum_Call_Count)) +
    facet_wrap(~dotw, ncol = 3) +
    scale_fill_viridis() +
    labs(title="Sum of EMS calls by day of the week") +
    mapTheme() + theme(legend.position = "bottom") 
```

```{r, fig.width=15, fig.height=15}
EMS_Call.panel %>% 
  group_by(week, uniqueID) %>%
  summarize(Sum_Call_Count = sum(Call_Count)) %>%
  ggplot() + geom_sf(aes(fill = Sum_Call_Count)) +
    facet_wrap(~week, ncol = 3) +
    scale_fill_viridis() +
    labs(title="Sum of EMS calls by week") +
    mapTheme() + theme(legend.position = "bottom") 
```

```{r}
as.data.frame(EMS_Call.panel) %>%
  group_by(interval60) %>% 
  summarize(Call_Count = sum(Call_Count)) %>%
  left_join(weather.Panel) %>%
  mutate(isPercip = ifelse(Percipitation > 0,"Rain", "None")) %>%
    group_by(week = week(interval60), isPercip) %>%
      summarize(Mean_Call_Count = mean(Call_Count)) %>%
    ggplot(aes(isPercip, Mean_Call_Count)) + 
      geom_bar(stat = "identity") +
      facet_wrap(~week,ncol=9) +
      labs(title="Does EMS Calls vary when it's raining?",
           subtitle="Mean call count by week; June through August, 2017",
           x="Percipitation", y="Mean Call Count") +
      plotTheme() + theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

```{r}
as.data.frame(EMS_Call.panel) %>%
  group_by(interval60) %>% 
  summarize(Call_Count = sum(Call_Count)) %>%
  left_join(weather.Panel) %>%
    mutate(week = week(interval60)) %>%
  ggplot(aes(Temperature, Call_Count)) + 
    geom_point() + facet_wrap(~week) + geom_smooth(method = "lm", se= FALSE) +
    plotTheme() +
  labs(title="Call Count as a fuction of Temperature by week",
           subtitle="Call count by week; June through August, 2017",
           x="Temperature", y="Call Trip Count")
```

```{r}
as.data.frame(EMS_Call.panel) %>%
  group_by(interval60) %>% 
  summarize(Call_Count = sum(Call_Count)) %>%
  left_join(weather.Panel) %>%
  mutate(isHot = ifelse(Temperature > 86,"Hot", "None")) %>%
    group_by(week = week(interval60), isHot) %>%
      summarize(Mean_Call_Count = mean(Call_Count)) %>%
    ggplot(aes(isHot, Mean_Call_Count)) + 
      geom_bar(stat = "identity") +
      facet_wrap(~week,ncol=9) +
      labs(title="Does EMS Call vary when it's too hot?",
           subtitle="Mean call count by week; June through August, 2017",
           x="Temperature", y="Mean Call Count") +
      plotTheme() + theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

```{r}
week26 <-
  EMS_fishnet %>%
  filter(week == 26 & dotw == "Mon")

week26.panel <-
   expand.grid(interval60 = seq(floor_date(ymd_hms(min(week26$call_date_and_time)), unit = "hour"),floor_date(ymd_hms(max(week26$call_date_and_time)), unit = "hour"), by = '60 mins'), 
              uniqueID = unique(fishnet$uniqueID)) 
```

```{r}
EMS_Call.animation.data <-
  week26 %>%
    mutate(Call_Counter = 1) %>%
    right_join(week26.panel) %>% 
    group_by(interval60, uniqueID) %>%
    summarize(Call_Count = sum(Call_Counter, na.rm=T)) %>% 
    left_join(fishnet,by=c("uniqueID")) %>%
    st_sf() %>%
    mutate(Calls = case_when(Call_Count == 0 ~ "0 calls",
                             Call_Count > 0 & Call_Count <= 1 ~ "1 call",
                             Call_Count > 1 & Call_Count <= 3 ~ "2-3 calls",
                             Call_Count > 3 & Call_Count <= 5 ~ "4-5 calls",
                             Call_Count > 5 ~ "5+ calls")) %>%
           mutate(Calls  = factor(Calls, levels=c("0 calls","1 call","2-3 calls","4-5 calls","5+ calls")))
```

```{r}
EMS_Call_animation <-
  ggplot() +
  geom_sf(data=EMS_Call.animation.data, aes(fill=Calls)) +
  scale_fill_manual(values = palette5) +
  labs(title = "EMS Calls for one day in June 2018, Virginia Beach",
       subtitle = "60 minute intervals: {current_frame}") +
  transition_manual(interval60) +
  mapTheme()

animate(EMS_Call_animation, duration=24)
```

```{r}
anim_save("EMS Calls Virginia Beach.gif", EMS_Call_animation, duration=24)
```

```{r}
census_fishnet <- 
  fishnet[c(1)] %>% 
  st_join(vbCensus[-c(2,3)], st_intersects, largest=TRUE) %>% 
  left_join(st_set_geometry(vbCensus, NULL), by=c('GEOID')) %>% 
  st_set_geometry(NULL)
```

```{r}
plotData.census <- 
  as.data.frame(EMS_Call.panel) %>%
    filter(week == 26) %>%
  group_by(uniqueID) %>% 
  summarize(Call_Count = sum(Call_Count))  %>%
    left_join(census_fishnet, by=c("uniqueID")) %>%
    filter(Variable == "Median_Household_Income" | Variable == "Mean_Commute_Time_for_Workers" |
           Variable == "Percent_Taking_Public_Trans" | Variable == "Percent_White" | Variable == "Percent_Single_Male"| Variable == "Total_Households_with_65yrs_and_Over") 
```

```{r}
correlation.census <-
  plotData.census %>%
  group_by(Variable) %>%  
  summarize(correlation = round(cor(Value, Call_Count),2))
  
correlation.census
```

```{r}
ggplot(plotData.census, aes(Value,Call_Count)) + geom_point() + geom_smooth(method="lm", se = F) +
  facet_wrap(~Variable, scales="free", ncol=2) +
  geom_text(data=correlation.census, aes(label=paste("R =", correlation)),
            colour = "blue", x=-Inf, y=Inf, hjust=-0.1, vjust=1.2) +
  plotTheme() +
  labs(title="One week of EMS Calls by Census Tract\nas a function of selected Census variables")
```

```{r, fig.width=15}
as.data.frame(EMS_Call.panel) %>%
  group_by(uniqueID) %>% 
  summarize(Call_Count = sum(Call_Count)) %>%
ggplot(aes(Call_Count)) + 
  geom_histogram(binwidth = 1) +
  labs(title = "Distribution of EMS Calls by grid cell")
```

```{r}
vbCensus_wide <- spread(vbCensus, Variable, Value)
```

```{r}
census_fishnet_wide <- 
  fishnet[c(1)] %>% 
  st_join(vbCensus_wide[-c(2:18)], st_intersects, largest = TRUE) %>% 
  left_join(st_set_geometry(vbCensus_wide, NULL), by=c('GEOID')) %>% 
  st_set_geometry(NULL)
```

```{r}
EMS_Call_final <- EMS_Call.panel %>%
  left_join(census_fishnet_wide, by = c("uniqueID"))
EMS_Call_final <- EMS_Call_final[is.na(EMS_Call_final$GEOID) != TRUE,] 
EMS_Call_final <- EMS_Call_final[is.na(EMS_Call_final$DPOP_CY) != TRUE,]
```
4
```{r}
EMS_Call.panel$hours <- hour(EMS_Call.panel$interval60)
```

```{r}
EMS_Call_final %>%
  group_by(hour, dotw) %>%
  summarise(
  Call_Count = sum(Call_Count)) %>%
ggplot(aes(x=hour, 
           y=dotw, 
           fill=Call_Count)) + geom_tile() + scale_fill_gradient(low = "#E4FFFF", high = "#EF200A", name = 'Count of EMS Calls')
```

