---
title: "Modeling"
author: "Yujing Wu"
date: "12/3/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(pscl)
library(tidyr)
library(tidyverse)
library(sf)
library(RSocrata)
library(lubridate)
library(tigris)
library(tidycensus)
library(gganimate)
library(viridis)
library(riem)
library(gridExtra)
library(knitr)
library(kableExtra)
#library(stargazer)

mapTheme <- function(base_size = 12) {
  theme(
    text = element_text( color = "black"),
    plot.title = element_text(size = 14,colour = "black"),
    plot.subtitle=element_text(face="italic"),
    plot.caption=element_text(hjust=0),
    axis.ticks = element_blank(),
    panel.background = element_blank(),axis.title = element_blank(),
    axis.text = element_blank(),
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    panel.grid.minor = element_blank(),
    panel.border = element_rect(colour = "black", fill=NA, size=2)
  )
}

plotTheme <- function(base_size = 12) {
  theme(
    text = element_text( color = "black"),
    plot.title = element_text(size = 14,colour = "black"),
    plot.subtitle = element_text(face="italic"),
    plot.caption = element_text(hjust=0),
    axis.ticks = element_blank(),
    panel.background = element_blank(),
    panel.grid.major = element_line("grey80", size = 0.1),
    panel.grid.minor = element_blank(),
    panel.border = element_rect(colour = "black", fill=NA, size=2),
    strip.background = element_rect(fill = "grey80", color = "white"),
    strip.text = element_text(size=12),
    axis.title = element_text(size=12),
    axis.text = element_text(size=10),
    plot.background = element_blank(),
    legend.background = element_blank(),
    legend.title = element_text(colour = "black", face = "italic"),
    legend.text = element_text(colour = "black", face = "italic"),
    strip.text.x = element_text(size = 14)
  )
}

palette5 <- c("#eff3ff","#bdd7e7","#6baed6","#3182bd","#08519c")
palette4 <- c("#D2FBD4","#92BCAB","#527D82","#123F5A")
palette3 <- c("#6baed6","#3182bd","#08519c")
palette2 <- c("#6baed6","#08519c")

qBr <- function(df, variable, rnd) {
  if (missing(rnd)) {
    as.character(quantile(round(df[[variable]],0),
                          c(.01,.2,.4,.6,.8), na.rm=T))
  } else if (rnd == FALSE | rnd == F) {
    as.character(formatC(quantile(df[[variable]]), digits = 3),
                          c(.01,.2,.4,.6,.8), na.rm=T)
  }
}

q5 <- function(variable) {as.factor(ntile(variable, 5))}
```

```{r}
EMS_Call_final <- 
  EMS_Call_final %>% 
  mutate(hour = hour(interval60)) %>%
  mutate(log_DPOP = log(DPOP_CY))
```

```{r}
EMS_Call.Train <- filter(EMS_Call_final, week < 26)
EMS_Call.Test <- filter(EMS_Call_final, week >= 26)
```

```{r}
regression1 <- 
  zeroinfl(Call_Count ~ hour + log_DPOP + lagHour + lag2Hours + dotw + name + countAccident| 1, data = EMS_Call.Train)
```

```{r}
EMS_Call.Test.weekNest <- 
  EMS_Call.Test %>%
  nest(-week) 

EMS_Call.Test.weekNest
```

```{r}
model_pred <- function(dat, fit){
   pred <- predict(fit, newdata = dat)}
```

```{r}
week_predictions <- 
  EMS_Call.Test.weekNest %>% 
    mutate(A_Time_FE = map(.x = data, fit = regression1, .f = model_pred))

week_predictions 
```

```{r}
week_predictions <-
  week_predictions %>% 
    gather(Regression, Prediction, -data, -week) %>%
    mutate(Observed = map(data, pull, Call_Count),
           Absolute_Error = map2(Observed, Prediction,  ~ abs(.x - .y)),
           MAE = map_dbl(Absolute_Error, mean),
           sd_AE = map_dbl(Absolute_Error, sd))

week_predictions 
```

```{r}
EMS_Call.Test.weekNest %>%
  mutate(Call_Count = map(data, pull, Call_Count),
         Mean_Call_Count = map_dbl(Call_Count, mean))
```

```{r}
week_predictions %>% 
    mutate(interval60 = map(data, pull, interval60),
           uniqueID = map(data, pull, uniqueID)) %>%
    dplyr::select(interval60, uniqueID, Observed, Prediction, Regression) %>%
    unnest() %>%
    gather(Variable, Value, -Regression, -interval60, -uniqueID) %>%
    group_by(Regression, Variable, interval60) %>%
    summarize(Value = mean(Value)) %>%
    ggplot(aes(interval60, Value, colour=Variable)) + 
      geom_line(size = 1.1) + 
      facet_wrap(~Regression, ncol=1) +
      scale_colour_manual(values = palette2) +
      labs(title = "Mean Predicted/Observed EMS Calls by hourly interval", 
           subtitle = "Virginia Beach; A test set of 3 weeks in December", x = "Hour", y= "EMS Calls") +
      plotTheme()
```

```{r}
filter(week_predictions, Regression == "A_Time_FE") %>% 
  unnest() %>% 
  st_sf() %>%
  dplyr::select(uniqueID, Prediction, geometry) %>%
  gather(Variable, Value, -uniqueID, -geometry) %>%
    group_by(Variable, uniqueID) %>%
    summarize(Mean_Prediction = mean(Value)) %>%
    ggplot() + 
      geom_sf(aes(fill = Mean_Prediction)) +
      scale_fill_viridis() +
      labs(title="Mean prediction by grid") +
      mapTheme() + theme(legend.position="bottom")
```

```{r}
filter(week_predictions, Regression == "A_Time_FE") %>% 
  unnest() %>% 
  st_sf() %>%
  dplyr::select(uniqueID, Absolute_Error, geometry) %>%
  gather(Variable, Value, -uniqueID, -geometry) %>%
    group_by(Variable, uniqueID) %>%
    summarize(MAE = mean(Value)) %>%
    ggplot() + 
      geom_sf(aes(fill = MAE)) +
      scale_fill_viridis() +
      labs(title="Mean Absolute Error by grid") +
      mapTheme() + theme(legend.position="bottom")
```

```{r}
filter(week_predictions, Regression == "A_Time_FE") %>% 
  unnest() %>% 
  st_sf() %>%
  dplyr::select(uniqueID, Absolute_Error, geometry, interval60) %>%
  gather(Variable, Value, -interval60, -uniqueID, -geometry) %>%
  filter(wday(interval60, label = TRUE) == "Mon" & week(interval60) == 28) %>%
    group_by(hour = hour(interval60), uniqueID) %>%
      summarize(MAE = mean(Value)) %>%
      ggplot() + 
        geom_sf(aes(fill = MAE)) +
        facet_wrap(~hour, ncol = 8) +
        scale_fill_viridis() +
        labs(title="Mean absolute call count error by tract and hour",
             subtitle = "For the Monday of Week 28") +
        mapTheme() + theme(legend.position="bottom")
```
```{r}
crossValidate <- function(dataset, id, dependentVariable, indVariables) {

allPredictions <- data.frame()
cvID_list <- unique(dataset[[id]])

for (i in cvID_list) {

  thisFold <- i
  cat("This hold out fold is", thisFold, "\n")

  fold.train <- filter(dataset, dataset[[id]] != thisFold) %>% as.data.frame() %>% 
                dplyr::select(id, geometry, indVariables, dependentVariable)
  fold.test  <- filter(dataset, dataset[[id]] == thisFold) %>% as.data.frame() %>% 
                dplyr::select(id, geometry, indVariables, dependentVariable)
  
  regression <-
    zeroinfl(Call_Count ~ .|1, 
      data = fold.train %>% 
      dplyr::select(-geometry, -id))
  
  thisPrediction <- 
    mutate(fold.test, Prediction = predict(regression, fold.test, type = "response"))
    
  allPredictions <-
    rbind(allPredictions, thisPrediction)
    
  }
  return(st_sf(allPredictions))
}
```

```{r}
reg.cv <- crossValidate(
  dataset = EMS_Call_final,
  id = "name",
  dependentVariable = "Call_Count",
  indVariables = c("hour","log_DPOP", "lagHour", "lag2Hours", "dotw", "name", "countAccident")) %>%
    dplyr::select(name = name, Call_Count, Prediction, geometry)
```

```{r}
reg.summary <- 
  
    mutate(reg.cv,           Error = Call_Count - Prediction,
                             CVBY = "Random k-fold CV: neighborhoods")%>%
    st_sf() 

reg.cvsummary <- reg.summary %>%
  mutate(MAE = abs(Error)) %>%
  group_by(name) %>%
  summarise(
  MAE = mean(MAE, na.rm = TRUE)
)
```

```{r}
ggplot(reg.cvsummary, aes(MAE)) + 
  geom_histogram(bins = 10, colour="white", fill = "#FA7800") +
  labs(title="Distribution of MAE", subtitle = "Cross validation; cvID = Neighborhood",
       x="Mean Absolute Error", y="Count") +
  plotTheme()
```

